---

- name: debian based
  become: true
  when:
    - ansible_facts.os_family | lower == 'debian'
    - php_version | int == 8
  block:
    - name: debian
      when:
        ansible_facts.distribution | lower == "debian"
      block:
        - name: Download Sury archive keyring .deb
          ansible.builtin.get_url:
            url: https://packages.sury.org/debsuryorg-archive-keyring.deb
            dest: /var/cache/apt/debsuryorg-archive-keyring.deb
            mode: "0644"
          become: true

        - name: Install Sury archive keyring package
          ansible.builtin.apt:
            deb: /var/cache/apt/debsuryorg-archive-keyring.deb
            state: present
            update_cache: false
          become: true
          register: debsuryorg_apt_key

        - name: add debsuryorg apt repository
          ansible.builtin.copy:
            dest: /etc/apt/sources.list.d/debsuryorg.sources
            content: |
              Types: deb
              URIs: https://packages.sury.org/php/
              Components: main
              Suites: {{ ansible_facts.distribution_release }}
              Signed-By: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
            mode: '0644'
          register: debsuryorg_apt_repository

    - name: ubuntu
      when:
        ansible_facts.distribution | lower == "ubuntu"
      block:
        - name: add php repository from PPA
          ansible.builtin.apt_repository:
            repo: ppa:ondrej/php
            codename: "{{ ansible_facts.distribution_release }}"

...
