---

systemd_lib_directory: /lib/systemd/system

php_defaults_packages:
  - "{{ php_package_name | default('php') }}{{ php_major_version }}"
  - "{{ php_package_name | default('php') }}{{ php_major_version }}-fpm"

php_conf_paths:
  - "/etc/{{ php_package_name | default('php') }}{{ php_major_version }}"

php_extension_conf_paths:
  - /etc/{{ php_package_name | default('php') }}{{ php_major_version }}/conf.d

php_fpm_daemon: "{{ php_package_name | default('php') }}-fpm{{ php_major_version }}"

php_fpm_pool_user_default: http

php_fpm_conf_path: "/etc/{{ php_package_name | default('php') }}{{ php_major_version }}"

php_fpm_pool_conf_path: "/etc/{{ php_package_name | default('php') }}{{ php_major_version }}/php-fpm.d"

# php_webserver_daemon: nginx

php_modules_conf_paths: "/etc/{{ php_package_name | default('php') }}{{ php_major_version }}/mods-available"
