---

- name: find php binaries
  ansible.builtin.find:
    paths:
      - "/usr/bin"
      - "/usr/sbin"
    file_type: file
    patterns:
      - "php-fpm*"
    recurse: false
  no_log: true
  register: found_binaries

- name: create custom fact file
  bodsch.core.facts:
    name: php_fpm
    facts:
      daemon: "{{ php_fpm_daemon }}"
      socket_directory: "{{ php_fpm_socket_directory }}"
      user: "{{ php_fpm_pool_user }}"
      group: "{{ php_fpm_pool_group }}"
      binary: "{{ found_binaries.files[0].path }}"
      legacy: "{{ 'true' if php_package_name == 'php-legacy' else 'false' }}"
      version:
        package: "{{ php_package_version }}"
        major: "{{ detected_php_version.available.major_version | default(omit) }}"
        full: "{{ php_version }}"

...
