---

- name: include OS specific configuration ({{ ansible_facts.distribution }} ({{ ansible_facts.os_family }}) {{ ansible_facts.distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.service_mgr | lower }}.yml"
        # eg. artixlinux
        - "{{ ansible_facts.distribution | lower | replace(' ', '') }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_facts.distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_facts.os_family | lower }}.yml"
        - default.yml
      skip: true

- name: detect ansible check_mode
  bodsch.core.check_mode:
  register: _check_mode

- name: define running_in_check_mode
  ansible.builtin.set_fact:
    running_in_check_mode: '{{ _check_mode.check_mode }}'

- name: assert missing defined php version
  ansible.builtin.assert:
    that:
      - php_version | int not in ["7", "8"]
    msg: php version is missing or wrong major version
    quiet: true

- name: assert wrong defined php_package_name
  when:
    - ansible_facts.distribution | lower == 'archlinux' or
      ansible_facts.distribution | lower | replace(' ', '') == 'artixlinux'
  ansible.builtin.assert:
    that:
      - php_package_name | string in ["php", "php-legacy"]
    msg: "php_package_name is wrong.\nplease use only `php` or `php-legacy`\nfound: {{ php_package_name }}"
    quiet: true

- name: do facts module to get latest information
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

- name: define pool user
  ansible.builtin.set_fact:
    php_fpm_pool_user: "{{ php_fpm_pool_user_default }}"
  when:
    - not php_fpm_pool_user is defined or php_fpm_pool_user | length == 0

- name: re-define primary group
  when:
    - not php_fpm_pool_group is defined or php_fpm_pool_group | length == 0
  block:
    - name: "find primary group for user '{{ php_fpm_pool_user }}'"
      ansible.builtin.getent:
        database: group
        key: "{{ php_fpm_pool_user }}"
        split: ':'

    - name: define php_fpm group
      ansible.builtin.set_fact:
        _php_fpm_group: "{{ ansible_facts['getent_group'] | list | first }}"
      when:
        - ansible_facts['getent_group'] is defined
        - ansible_facts['getent_group'] | default([]) | count > 0

    - name: "set php_fpm_pool_group '{{ _php_fpm_group }}'"
      ansible.builtin.set_fact:
        php_fpm_pool_group: "{{ _php_fpm_group }}"
      when:
        - _php_fpm_group is defined

- name: assert pool group
  ansible.builtin.assert:
    that:
      - php_fpm_pool_group is defined or php_fpm_pool_group | length == 0
    msg: no php-fpm pool group detected
    quiet: true

...
