---

php_defaults_packages:
  - php-common
  - php-cli

php_dependencies:
  - gnupg

php_conf_paths:
  - /etc/php/{{ php_version }}/fpm
  - /etc/php/{{ php_version }}/cli

php_extension_conf_paths:
  - /etc/php/{{ php_version }}/fpm/conf.d
  - /etc/php/{{ php_version }}/cli/conf.d

php_modules_conf_paths: /etc/php/{{ php_version }}/mods-available

...
