---

# READ local_facts
- name: set local fact for container
  ansible.builtin.set_fact:
    installed_php_version: "{{ ansible_facts.local.php.version }}"
  when:
    - ansible_facts.local.php is defined
    - ansible_facts.local.php.version is defined
    - ansible_facts.local.php.version | length != 0

# - name: d
#   debug:
#     msg: "{{ installed_php_version | default('none')}}"

- name: ensure configuration directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    follow: true
  with_community.general.flattened:
    - "{{ php_conf_paths }}"
    - "{{ php_extension_conf_paths }}"

- name: create php.ini configuration files
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ item }}/php.ini"
    owner: root
    group: root
    mode: "0644"
    backup: true
  loop:
    "{{ php_conf_paths }}"
  loop_control:
    label: "{{ item }}"
  vars:
    _sapi: "{{ item | basename }}"
    php_ini_effective: >-
      {{ php_ini_defaults
         | combine(php_ini, recursive=True)
         | combine(php_ini_sapi[_sapi] | default({}), recursive=True) }}
  when:
    - php_use_managed_ini | bool
...
