---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - php_ini_prepare

- name: install
  ansible.builtin.include_tasks: install.yml
  tags:
    - php_ini_install

- name: configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - php_ini_configure

...
