"""
Temporary file helper that keeps the file path usable during the context
lifetime and optionally removes the file afterwards.

This is useful on Windows, where `tempfile.NamedTemporaryFile` can cause
permission problems when the same file must be reopened by path while
still inside the context block.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, Sequence, Tuple, Union

from ansible_collections.bodsch.core.plugins.module_utils.checksum import Checksum
from ansible_collections.bodsch.php.plugins.module_utils.atomic_file import (
    AtomicFileWriter,
)
from ansible_collections.bodsch.php.plugins.module_utils.php_dataclasses import (
    ModuleDefinition,
)

TPL_MODULE = """; generated by ansible
{% if item is defined %}
{{ item }}
{% endif %}
"""


class PhpModule:
    """ """

    def __init__(
        self,
        module: Any,
        extension_directory: str,
        modules_path: str,
        is_php_branch: bool,
    ) -> None:

        self.module = module
        self.module.log(
            f"PhpModule::__init__(extension_directory: {extension_directory}, modules_path: {modules_path}, is_php_branch: {is_php_branch})"
        )

        self.extension_directory = extension_directory
        self.php_modules_path = modules_path
        self.is_php_branch = is_php_branch

        self.checksum = Checksum(module=self.module)

    def write_module_configuration(
        self,
        module_definition: ModuleDefinition,
    ) -> bool:
        """Write or remove a PHP module configuration file.

        The method applies version-specific normalization before rendering and
        writing the final configuration content. Idempotency is preserved through
        checksum comparison.

        Args:
            module_name: Logical module name used for the checksum cache file.
            file_name: Destination file path of the module configuration.
            data: Raw module configuration content.

        Returns:
            True if the configuration file content changed, otherwise False.
        """
        self.module.log(
            f"PhpModule::write_module_configuration(module_definition: {module_definition})"
        )

        module_file_name = os.path.join(
            self.php_modules_path,
            f"{module_definition.name}.ini",
        )

        module_name: str = module_definition.name
        file_name: str = module_file_name
        data = module_definition.content

        changed: bool = False
        new_checksum: str = ""
        old_checksum: str = ""

        normalized_data = self.__normalize_module_content(module_name, data)

        if normalized_data:
            rendered_data = self.__templated_data(normalized_data)

            self.module.log(f"  - normalized: {normalized_data}")
            self.module.log(f"  - rendered  : {rendered_data.strip()}")

            new_checksum = self.checksum.checksum(plaintext=rendered_data)

            self.module.log(f"  - new_checksum  : {new_checksum}")

            if os.path.exists(module_file_name):
                old_checksum = self.checksum.checksum_from_file(path=module_file_name)

            self.module.log(f"  - old_checksum  : {old_checksum}")

            changed = new_checksum != old_checksum

            if changed:
                self.__write_template(data=rendered_data, data_file=file_name)

            if os.path.exists(file_name):
                os.chmod(file_name, 0o0664)

        return changed

    def enable_module(
        self,
        module_file_name: str,
        module_link_names: Sequence[str],
    ) -> Tuple[bool, Dict[str, Dict[str, Union[str, bool]]]]:
        """Ensure activation symlinks exist and point to the requested file.

        Args:
            module_file_name: Source configuration file.
            module_link_names: Destination symlink paths.

        Returns:
            A tuple containing a changed flag and per-link result details.
        """
        result: Dict[str, Dict[str, Union[str, bool]]] = {}
        changed = False

        for link in module_link_names:
            result[link] = {}

            if os.path.islink(link) and os.readlink(link) == module_file_name:
                result[link].update(
                    {"msg": "link exists and is valid", "changed": False}
                )
                continue

            if not os.path.islink(link):
                self.create_link(module_file_name, link)
            else:
                self.create_link(module_file_name, link, True)

            result[link].update({"msg": f"link {link} created", "changed": True})
            changed = True

        return changed, result

    def disable_module(self, module_link_names: Sequence[str]) -> bool:
        """Remove activation links or files for a PHP module.

        Args:
            module_link_names: Paths to remove.

        Returns:
            C(True) when at least one path was removed, otherwise C(False).
        """
        self.module.log(
            f"PhpModule::disable_module(module_link_names: {module_link_names})"
        )

        changed = False

        for link in module_link_names:
            if os.path.lexists(link):
                os.remove(link)
                changed = True

        return changed

    def __normalize_module_content(
        self,
        module_name: str,
        data: str,
    ) -> str:
        """Normalize module configuration content for version-specific behavior.

        For PHP 8.5.x, the opcache extension must no longer be loaded explicitly via
        a zend_extension directive. Matching lines are removed while all other
        configuration lines remain unchanged.

        Args:
            module_name: Logical PHP module name.
            data: Raw module configuration content.

        Returns:
            Normalized configuration content.
        """
        if not self.is_php_branch:
            return data

        if module_name.lower() != "opcache":
            return data

        pattern = re.compile(
            r"(?im)^\s*zend_extension\s*=\s*opcache(?:\.so)?\s*(?:;.*)?\n?"
        )

        normalized = pattern.sub("", data)

        return normalized.strip() + "\n" if normalized.strip() else ""

    def __templated_data(self, data: Any) -> str:
        """Render raw configuration content through the internal Jinja template.

        Args:
            data: Raw configuration content.

        Returns:
            Rendered template output as a string.
        """
        from jinja2 import Template

        template = Template(TPL_MODULE)
        return str(template.render(item=data))

    def __write_template(
        self,
        data: str,
        data_file: str,
    ) -> None:
        """Write configuration and checksum files atomically.

        Args:
            data: Rendered configuration content.
            data_file: Destination configuration file path.
            checksum: Calculated checksum value.
            checksum_file: Destination checksum file path.
        """
        self.module.log(f"PHPModule::__write_template(data, data_file: {data_file})")

        file_handle = None

        data_path = Path(data_file)
        data_path.parent.mkdir(parents=True, exist_ok=True)

        self.module.log(f"  - file: {data_file}")
        try:
            with AtomicFileWriter(
                destination=data_file,
                mode="w",
                encoding="utf-8",
            ) as file_handle:
                # self.module.log(f"  - tmp_name: {file_handle.name}")
                # self.module.log(data)

                file_handle.write(data)

            exists = data_path.exists()
            self.module.log(f"  - destination exists after commit: {exists}")

            if not exists:
                raise OSError(
                    f"Atomic write reported success, but destination is missing: {data_file}"
                )

            os.chmod(data_file, 0o0664)

        except (FileNotFoundError, NotADirectoryError, PermissionError, OSError) as exc:
            self.module.log(f"ERROR: Atomic file write failed: {exc}")
            raise
