---

- name: install dependencies
  ansible.builtin.package:
    name: "{{ php_dependencies }}"
    state: present
  when:
    - php_dependencies | default([]) | count > 0

- name: debian based
  become: true
  when:
    - ansible_facts.os_family | lower == 'debian'
    - php_version | int == 8
  block:
    - name: debian
      when:
        ansible_facts.distribution | lower == "debian"
      bodsch.core.apt_sources:
        name: debsuryorg-archive
        filename: debsuryorg-archive.sources
        uris:
          - https://packages.sury.org/php/
        suites: "{{ ansible_facts.distribution_release | lower }}"
        components:
          - main
        signed_by: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
        key:
          method: deb
          url: "https://packages.sury.org/debsuryorg-archive-keyring.deb"
          dest: "/var/cache/apt/debsuryorg-archive-keyring.deb"
        update_cache: true

    - name: ubuntu
      when:
        ansible_facts.distribution | lower == "ubuntu"
      block:
        - name: add php repository from PPA
          ansible.builtin.apt_repository:
            repo: ppa:ondrej/php
            codename: "{{ ansible_facts.distribution_release }}"

...
