---

galaxy_info:
  role_name: pie
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to install php extensions with PIE (PHP Installer for Extensions)

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - programing
    - language
    - php
    - pie
    - extensions

dependencies: []

...
