---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - php-common

- name: repositories
  ansible.builtin.include_tasks: repositories/main.yml
  when:
    - ansible_facts.os_family | lower == 'debian'

- name: detect available php version
  ansible.builtin.include_tasks: detect_php_version.yml
  tags:
    - php-common

- name: install
  ansible.builtin.include_tasks: install.yml
  tags:
    - php-common

- name: ansible facts
  ansible.builtin.include_tasks: facts.yml
  tags:
    - php-common

...
