#!/usr/bin/python
# -*- coding: utf-8 -*-

# (c) 2022-2023, Bodo Schulz <bodo@boone-schulz.de>
# Apache-2.0 (see LICENSE or https://opensource.org/license/apache-2-0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

import hashlib
import os
import re
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union

from ansible.module_utils import distro
from ansible.module_utils.basic import AnsibleModule

# ---------------------------------------------------------------------------------------

DOCUMENTATION = r"""
---
module: php_modules
author: "Bodo Schulz (@bodsch) <bodo@boone-schulz.de>"
version_added: "1.0.0"

"""

EXAMPLES = r"""

"""

RETURN = r"""

"""

# ---------------------------------------------------------------------------------------


TPL_MODULE = """; generated by ansible
{% if item is defined %}
{{ item }}
{% endif %}
"""

# Example php -i output line:
#   extension_dir => /usr/lib/php/20230831 => /usr/lib/php/20230831
_EXT_DIR_RE = re.compile(
    r"^extension_dir\s*=>\s*(?P<configured>.*?)\s*=>", re.MULTILINE
)

try:
    # Python 3.8+
    from typing import Protocol  # type: ignore
except ImportError:  # pragma: no cover
    try:
        from typing_extensions import Protocol  # type: ignore
    except ImportError:  # pragma: no cover
        Protocol = object  # type: ignore[misc,assignment]


class AnsibleModuleLike(Protocol):
    """Typing surface for the Ansible module object used by this helper."""

    params: Mapping[str, Any]

    def run_command(
        self,
        args: Sequence[str],
        cwd: Optional[str] = None,
        environ_update: Optional[Mapping[str, str]] = None,
        check_rc: bool = True,
    ) -> Tuple[int, str, str]:
        ...

    def get_bin_path(self, arg: str, required: bool = False) -> Optional[str]:
        ...

    def log(self, msg: str = "", **kwargs: Any) -> None:
        ...


class PHPModules(object):
    """ """

    module = None

    def __init__(self, module: AnsibleModuleLike):
        """ """
        self.module = module

        self.module.log("PHPModules::__init__()")

        self.php_modules = module.params.get("php_modules")
        self.php_modules_path = module.params.get("php_modules_path")
        self.dest = module.params.get("dest")
        self.force = module.params.get("force")

        self.php_modules_cache_directory = str(
            Path.home() / ".ansible" / "cache" / "php"
        )

        self.php_binary = self.module.get_bin_path("php", False)

        (self.distribution, self.version, self.codename) = distro.linux_distribution(
            full_distribution_name=False
        )

        # self.module.log(f"  - distribution    : {str(self.distribution).lower()}")
        # self.module.log(f"  - php_modules_path: {self.php_modules_path}")

        if str(self.distribution).lower() in [
            "archlinux",
            "arch",
        ] and "php-legacy" in str(self.php_modules_path):
            self.php_binary = self.module.get_bin_path("php-legacy", False)

    def run(self) -> Dict[str, Any]:
        """ """
        self.module.log("PHPModules::run()")

        if not self.__create_directory(self.php_modules_cache_directory):
            return dict(
                failed=True,
                changed=False,
                msg=f"Unable to create cache directory '{self.php_modules_cache_directory}'.",
            )

        result_state: List[Dict[str, Any]] = []

        extension_directory, err = self.find_extension_dir()

        if not extension_directory:
            return dict(failed=True, msg=err)

        if isinstance(self.php_modules, list):
            for module_item in self.php_modules:
                """ """
                changed = False
                w_changed = False
                e_changed = False

                module_state_msg = None
                res: Dict[str, Any] = {}

                module_name = module_item.get("name")
                module_state = self.__strtobool(module_item.get("enabled", False))
                module_priority = module_item.get("priority", 10)
                module_content = module_item.get("content", None)
                module_file_name = os.path.join(
                    self.php_modules_path, f"{module_name}.ini"
                )
                module_link_names: List[str] = []

                for path in self.dest:
                    module_link_names.append(
                        os.path.join(
                            path, "conf.d", f"{module_priority}-{module_name}.ini"
                        )
                    )

                res[module_name] = dict()

                if module_content:

                    w_changed = self.write_module_configuration(
                        module_name, module_file_name, module_content
                    )

                    if w_changed:
                        module_state_msg = "module sucessful written"

                    if module_state:
                        e_changed, msg = self.enable_module(
                            module_file_name, module_link_names
                        )

                        if e_changed:
                            if module_state_msg:
                                module_state_msg += " and enabled"
                            else:
                                module_state_msg = "module sucessful enabled"

                    changed = w_changed or e_changed

                    res[module_name].update({"changed": changed})
                    if changed and module_state_msg:
                        res[module_name].update({"state": module_state_msg})

                if not module_state:
                    changed = self.disable_module(module_link_names)

                    if changed:
                        module_state_msg = "module succesfull disabled."

                        res[module_name].update({"state": module_state_msg})

                    res[module_name].update({"changed": changed})

                if len(res) > 0:
                    result_state.append(res)

        combined_d = {key: value for d in result_state for key, value in d.items()}
        changed = len({k: v for k, v in combined_d.items() if v.get("changed")}) > 0

        result = dict(changed=changed, failed=False, msg=result_state)

        self.module.log(msg=f"= result {result}")

        return result

    def find_extension_dir(self) -> Tuple[Optional[str], Optional[str]]:
        """ """
        self.module.log("PHPModules::find_extension_dir()")

        extension_directory: Optional[str] = None
        error_msg: Optional[str] = None

        if self.php_binary:

            args = [self.php_binary, "-i"]
            rc, out, err = self.__exec(args, check_rc=False)

            if rc == 0:
                error_msg = None
                extension = _EXT_DIR_RE.search(out)

                if extension:
                    extension_directory = extension.group("configured").strip()
            else:
                error_msg = err

        else:
            error_msg = "PHP does not appear to be installed in the default paths."

        # self.module.log(msg=f"{extension_directory}, {error_msg}")

        return extension_directory, error_msg

    def create_link(self, source: str, destination: str, force: bool = False) -> None:
        """ """
        self.module.log(
            f"PHPModules::create_link(source: {source}, destination: {destination}, force: {force})"
        )

        destination_path = Path(destination)
        destination_path.parent.mkdir(parents=True, exist_ok=True)

        if force:
            try:
                destination_path.unlink()
            except FileNotFoundError:
                pass
            os.symlink(source, destination)
            return

        if destination_path.exists() or destination_path.is_symlink():
            if destination_path.is_symlink():
                # replace an existing symlink (even when force=False), otherwise os.symlink would fail
                destination_path.unlink()
            else:
                # rename a regular file/dir
                os.rename(destination, f"{destination}.DIST")

        os.symlink(source, destination)

    def write_module_configuration(
        self, module_name: str, file_name: str, data: Optional[str] = None
    ) -> bool:
        """ """
        self.module.log(
            f"PHPModules::write_module_configuration(module_name: {module_name}, file_name: {file_name}, data)"
        )

        checksum_file = os.path.join(
            self.php_modules_cache_directory, f"{module_name}.checksum"
        )

        if not data:
            if os.path.exists(file_name):
                os.remove(file_name)
            if os.path.exists(checksum_file):
                os.remove(checksum_file)

            return False

        rendered_data = self.__templated_data(data)

        changed, new_checksum, old_checksum = self.__has_changed(
            file_name, checksum_file, rendered_data
        )

        if changed:
            self.__write_template(
                data=rendered_data,
                data_file=file_name,
                checksum=new_checksum,
                checksum_file=checksum_file,
            )

        return changed

    def enable_module(
        self, module_file_name: str, module_link_names: Sequence[str]
    ) -> Tuple[bool, Dict[str, Dict[str, Union[str, bool]]]]:
        """ """
        self.module.log(
            f"PHPModules::enable_module(module_file_name: {module_file_name}, module_link_names: {module_link_names})"
        )

        result: Dict[str, Dict[str, Union[str, bool]]] = {}
        changed = False

        for link in module_link_names:
            result[link] = dict()

            if os.path.islink(link) and os.readlink(link) == module_file_name:
                result[link].update(
                    {"msg": "link exists and is valid", "changed": False}
                )
                continue

            if not os.path.islink(link):
                self.create_link(module_file_name, link)
            else:
                # broken/outdated symlink
                self.create_link(module_file_name, link, True)

            result[link].update({"msg": f"link {link} created", "changed": True})
            changed = True

        return changed, result

    def disable_module(self, module_link_names: Sequence[str]) -> bool:
        """ """
        self.module.log(
            f"PHPModules::disable_module(module_link_names: {module_link_names})"
        )

        changed = False

        for link in module_link_names:
            if os.path.exists(link):
                os.remove(link)
                changed = True

        return changed

    def __write_template(
        self, data: str, data_file: str, checksum: str, checksum_file: str
    ) -> None:
        """ """
        # self.module.log(
        #     f"PHPModules::__write_template(data: {data}, data_file: {data_file}, checksum: {checksum}, checksum_file: {checksum_file})"
        # )

        data_path = Path(data_file)
        data_path.parent.mkdir(parents=True, exist_ok=True)

        # Atomic write: write to temp file in the same directory and replace.
        with NamedTemporaryFile(
            "w", delete=False, dir=str(data_path.parent), encoding="utf-8"
        ) as tf:
            tf.write(data)
            tmp_name = tf.name

        os.replace(tmp_name, data_file)

        checksum_path = Path(checksum_file)
        checksum_path.parent.mkdir(parents=True, exist_ok=True)

        with NamedTemporaryFile(
            "w", delete=False, dir=str(checksum_path.parent), encoding="utf-8"
        ) as tf:
            tf.write(checksum)
            tmp_checksum = tf.name

        os.replace(tmp_checksum, checksum_file)

    def __checksum(self, plaintext: str) -> str:
        """ """
        # self.module.log(f"PHPModules::__checksum(plaintext: {plaintext})")

        _bytes = plaintext.encode("utf-8")
        _hash = hashlib.sha256(_bytes)
        return _hash.hexdigest()

    def __templated_data(self, data: Any) -> str:
        """
        generate data from dictionary
        """
        # self.module.log(f"PHPModules::__templated_data(data: {data})")

        from jinja2 import Template

        tm = Template(TPL_MODULE)
        d = tm.render(item=data)

        return d

    def __has_changed(
        self, data_file: str, checksum_file: str, rendered_data: str
    ) -> Tuple[bool, str, str]:
        """ """
        # self.module.log(
        #     f"PHPModules::__has_changed(data_file: {data_file}, checksum_file: {checksum_file}, data: {rendered_data})"
        # )

        old_checksum = ""

        if not os.path.exists(data_file) and os.path.exists(checksum_file):
            """ """
            os.remove(checksum_file)

        if os.path.exists(checksum_file):
            with open(checksum_file, "r", encoding="utf-8") as f:
                first_line = f.readline()
                old_checksum = first_line.strip()

        new_checksum = self.__checksum(rendered_data)

        if self.force:
            return True, new_checksum, old_checksum

        # Self-heal: also validate current on-disk content to avoid stale checksum cache.
        file_checksum: Optional[str] = None
        if os.path.exists(data_file):
            with open(data_file, "r", encoding="utf-8") as f:
                file_checksum = self.__checksum(f.read())

        changed = (old_checksum != new_checksum) or (
            file_checksum is not None and file_checksum != new_checksum
        )

        return changed, new_checksum, old_checksum

    def __create_directory(self, directory: Union[str, Path]) -> bool:
        """ """
        # self.module.log(f"PHPModules::__create_directory(dir: {directory})")

        try:
            os.makedirs(str(directory), exist_ok=True)
        except Exception:
            return False

        return os.path.isdir(str(directory))

    def __strtobool(self, val: Any) -> bool:
        """
        Convert a string representation of truth to true (1) or false (0).

        True values are 'y', 'yes', 't', 'true', 'on', and '1';
        False values are 'n', 'no', 'f', 'false', 'off', and '0'.
        raises ValueError if 'val' is anything else.
        """
        # self.module.log(f"PHPModules::__strtobool(val: {val})")

        if isinstance(val, bool):
            return val

        if isinstance(val, str):
            _val = val.lower()
            if _val in ("y", "yes", "t", "true", "on", "1"):
                return True
            elif _val in ("n", "no", "f", "false", "off", "0"):
                return False
            else:
                raise ValueError(f"invalid truth value {val}")

        return bool(val)

    def __exec(
        self,
        args: Sequence[str],
        environ_update: Optional[Dict[str, str]] = None,
        check_rc: bool = True,
    ) -> Tuple[int, str, str]:
        """
        Execute a prepared command via the Ansible module's `run_command()`.

        Args:
            args: Full argument vector to execute (already includes `occ_base_args`).
            environ_update: Environment variables added/overridden for this process.
                Example: {"OC_PASS": "<secret>"} used together with `--password-from-env`.
            check_rc: If True, Ansible will raise a failure on non-zero return code.

        Returns:
            Tuple of (rc, out, err):
                - rc: return code (int)
                - out: stdout (str)
                - err: stderr (str)

        Security:
            Avoid logging secrets in `environ_update`. If you need debug logging, consider
            redacting sensitive keys before writing to module logs.
        """
        # self.module.log(
        #     msg=f"PHPModules::__exec(args: {args}, environ_update: {environ_update}, check_rc: {check_rc})"
        # )

        rc, out, err = self.module.run_command(
            list(args), environ_update=environ_update, check_rc=check_rc
        )

        return rc, out, err


def main():
    """ """
    specs = dict(
        php_modules=dict(required=True, type=list),
        php_modules_path=dict(required=True, type=str),
        dest=dict(required=True, type=list),
        force=dict(required=False, type=bool, default=False),
    )

    module = AnsibleModule(
        argument_spec=specs,
        supports_check_mode=False,
    )

    helper = PHPModules(module)
    result = helper.run()

    module.log(msg=f" = result : '{result}'")

    module.exit_json(**result)


# import module snippets
if __name__ == "__main__":
    main()

"""

php -r '$all = get_loaded_extensions();
    foreach($all as $i) {
        $ext = new ReflectionExtension($i);
        $ver = $ext->getVersion();
        echo "$i - $ver" . PHP_EOL;
    }'
"""
